name: cardswop_server
description: server part of the cardswop web app powered by Dart Frog
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cardswop_shared:
    path: shared/
  dart_frog: ^0.3.0
  json_annotation: ^4.8.1
  orm: ^3.4.3
 

  


dev_dependencies:
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0
