name: cardswop_server
description: server part of the cardswop web app powered by Dart Frog
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cardswop_shared:
    git: https://github.com/qoeru/cardswop-shared.git
    # path: '../shared/'
  dart_frog: ^0.3.0 
  stormberry: ^0.13.1



dev_dependencies:
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0
